### PR TITLE
fix: return invalid pathlint and messageLint only

### PR DESCRIPTION
**Pull request by shinjiescorido**
Issue S-06698

### CODE REVIEW

**Comment by shinjiescorido** [comment]
@openam @sydcanem @yamii

**Comment by openam** [comment]
Why are we adding the successful results and then deleting them. Wouldn't it just be easier not to add the results, https://github.com/sinet/pathlint/blob/master/lib/adapters/message-lint.js#L29-L34. If we just moved lines 33 and 34 into the `if ( !isBaseNameGood )` it would only push errors into the results.

You could do the same thing in `adapters/path-lint.js`

**Comment by shinjiescorido** [comment]
@openam .That was the first attempt. It raises a lot of errors during unit testing and its still be returning a json with the paths as keys with an empty object values "{}".

```
{ messageLint: { 'services/**/*.js': {} },
  pathLint:
   { 'services/**/*.js': {},
     'utilities/**/*.js': {},
     'test/**/*.js': {} } }
```

so then I decided to add logic instead on the final results and still ends up displaying it as a json data.

**Comment by yamii** [comment]
@shinjiescorido I agree with @openam into fixing that way rather than we loop through the results and remove the `success` results. If you think about it, isn't it better for `messageLint` and `pathLint` adapters? 

```
https://github.com/sinet/pathlint/blob/master/lib/adapters/message-lint.js
https://github.com/sinet/pathlint/blob/master/lib/adapters/path-lint.js
```

to only return the `fail` result?

as what mike commented you can both move this line https://github.com/sinet/pathlint/blob/master/lib/adapters/path-lint.js inside `if ( !isBaseNameGood ) {` so as with the `messageLint`

doing that it will give us something like this:

```
  services/**/*.js:
    services/v1/feedback/create.js:
      v1.feedback: false
pathLint:
  services/**/*.js:

  test/**/*.js:
```

so we also also have to do additional code in this file https://github.com/sinet/pathlint/blob/master/lib/index.js to really achieve our goal. Making it something like this.

```
  services/**/*.js:
    services/v1/feedback/create.js:
      v1.feedback: false
```

but it's up to you. we can do it in may ways. but the fix you've gave will add additional process so we recommend this instead.

**Comment by yamii** [comment]
please also omit the error stack trace. I can see the error stack trace when I have an error in linting 

```
{ messageLint:
   Error: linter: 2 error/s found.
       at /Users/Yami/Documents/Repository/observation/pathlint/lib/index.js:90:30
       at tryCatcher (/Users/Yami/Documents/Repository/observation/pathlint/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/Users/Yami/Documents/Repository/observation/pathlint/node_modules/bluebird/js/release/promise.js:504:31)
       at Promise._settlePromise (/Users/Yami/Documents/Repository/observation/pathlint/node_modules/bluebird/js/release/promise.js:561:18)
       at Promise._settlePromise0 (/Users/Yami/Documents/Repository/observation/pathlint/node_modules/bluebird/js/release/promise.js:606:10)
       at Promise._settlePromises (/Users/Yami/Documents/Repository/observation/pathlint/node_modules/bluebird/js/release/promise.js:685:18)
       at Async._drainQueue (/Users/Yami/Documents/Repository/observation/pathlint/node_modules/bluebird/js/release/async.js:138:16)
       at Async._drainQueues (/Users/Yami/Documents/Repository/observation/pathlint/node_modules/bluebird/js/release/async.js:148:10)
       at Immediate.Async.drainQueues [as _onImmediate] (/Users/Yami/Documents/Repository/observation/pathlint/node_modules/bluebird/js/release/async.js:17:14)
       at tryOnImmediate (timers.js:543:15)
```

just display the error message instead.

**Comment by shinjiescorido** [comment]
@openam  @yamii changes were already made. thanks

**Comment by yamii** [comment]
@shinjiescorido can you include fixing this one?

```
'v1.feedback.-‘
```

it should be failed, should only accept letters

**Comment by shinjiescorido** [comment]
👍 I also added the other special characters as well. thanks

**Comment by yamii** [comment]
OK! 💃

**Pull request merged**
